# These settings determine the behaviour of runbook.md's Runbook Validator bot
# https://github.com/financial-times/runbook.md

# Everything below is optional

runbooks:
  # All available settings are listed below

  # Disable checks for this repo
  # defaults to `false`
  disabled: false

  ### SUPPORT FOR MULTIPLE RUNBOOKS IN A SINGLE REPOSITORY

  # Fail checks if `any` | `all` | `none` runbooks fail validation
  # defaults to `any`
  failOn: any

  ### SUPPORT FOR UPDATING BIZ-OPS

  # Update valid Biz-Ops runbooks on merge to a specific branch
  #### IF YOUR DEPLOYMENTS ARE AUTOMATED (CircleCI, Heroku Pipelines)
  #### PLEASE INTEGRATE WITH CHANGE-API INSTEAD
  #### https://github.com/Financial-Times/change-api#change-api---v2
  # defaults to `false`
  updateOnMerge: true

  # Merges to this branch trigger Biz-Ops updates updateOnMerge is `true`
  # defaults to `master`
  updateBranch: master

  ### UPDATING BIZ-OPS REQUIRES EACH RUNBOOK TO BE TIED TO A VALID SYSTEM CODE
  # Mappings between paths and system codes
  # unless a custom mapping is specified here
  # runbook.md tries to parse the system code from the runbook's filename (format: my-sys-code_runbook.md)
  systemCodes:
    # paths are relative to root, omitting ./ (case-insensitive)
    mongo-hot-backup: runbooks/runbook.md
