# Default values for mongo-hot-backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  volumeMountPath: data/mongo-hot-backup
replicaCount: 2
image:
  repository: nexus.in.ft.com:5000/coco/mongo-hot-backup
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 384Mi

