# Default values for mongo-hot-backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  volumeMountPath: data/mongo-hot-backup
  s3Domain: s3-eu-west-1.amazonaws.com
  s3Bucket: "com.ft.upp.mongo-backup"
  cron: 0 15 * * *

replicaCount: 1


image:
  repository: nexus.in.ft.com:5000/coco/mongo-hot-backup
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 2560Mi
